modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "azusaconfig"
version = "${version}"
displayName = "AzusaConfig"
credits = "QuiltMC"
authors = "TexTrue, HO-Artisan"
description = '''
A library to bring the Quilt Loader's Config system into Fabric/Forge/NeoForge.
'''
logoFile = "icon.png"

[[dependencies.azusaconfig]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.azusaconfig]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"