org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.20.4
enabled_platforms=fabric,neoforge
yarn_mappings=1.20.4+build.3

archives_base_name=AzusaConfig
mod_version=0.1.3
maven_group=ho.artisan.azusaconfig

fabric_loader_version=0.16.2

neoforge_version=20.4.237

curseforge_id=970148
modrinth_id=12LahGY4

quiltconfig_version=1.3.2
quiltparsers_version=0.2.0
