modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "azusa_config"
version = "${version}"
displayName = "AzusaConfig"
credits = "QuiltMC"
authors = "TexTrue, HO-Artisan"
description = '''
A library to bring the Quilt Loader's Config system into Fabric/Forge/NeoForge.
'''
#logoFile = ""

[[dependencies.azusa_config]]
modId = "neoforge"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.azusa_config]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.azusa_config]]
modId = "architectury"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"